### ISSUE TITLE
configure bash file is missing

### ISSUE THREAD

**Issue by sr12zar** [tlwg/swath#4]
Please supply configure file so we can follow 'INSTALL' instructions.
(Configure file existed in previous versions - my latest is swath 0.5.3).

**Comment by thep** [comment]
I wonder if it's possible to disable tarballs provision on GitHub, as they're not intended to be used by users at all. What you get from it is a copy of version-controlled git snapshot, where you're supposed to run `./autogen.sh` to get all the rest files.

The user-ready tarballs can be downloaded from [linux.thai.net](https://linux.thai.net/pub/thailinux/software/swath/)

The reason is that we don't maintain auto-generated files in repository, as their contents vary with the autotools version you run.

**Comment by thep** [comment]
Meanwhile, I've added the link to official source release tarball in the release message:
https://github.com/tlwg/swath/releases/tag/v0.6.0

**Comment by pepa65** [comment]
If you link to https://linux.thai.net/ as the homepage or to https://linux.thai.net/pub/thailinux/software/swath/ as the download page from the Readme, that might be helpful, so people don't just start building from the repo.

**Comment by sr12zar** [comment]
Thank you. I downloaded the tar ball and build from that. All went well.
Now that is clearer on how we should build the package. Would it be
possible to explain this in INSTALL, NEWS, changelog etc. files so we know
how to build the package. Let us say, we are promoting Thai Linux with
'easy to build' approaches. ;-)

sr

**Comment by thep** [comment]
I've merged pull request #3 from @pepa65 which provided the explanation in INSTALL file. So, I'm closing this issue.

Besides, the released tarball will be attached to every release announcement on GitHub from now on, in addition to the GitHub ones. That should ease users at some degree.
